linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/google # all google packages
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/stretchr
